import { config, EntityManager, EntityType, AutoGeneratedKeyType, NamingConvention, IProperty, EntityManagerOptions } from 'breeze-client';

import { configuration } from './Configuration'

export function entityManagerFactory(): EntityManager {
    //NamingConvention.camelCase.setAsDefault();
    config.initializeAdapterInstance("uriBuilder", "json");
    let options: EntityManagerOptions;
    var em = new EntityManager({ serviceName: configuration.UrlForBreezeBackEndService })
    console.log("Naming Convention:");
    console.log(em.metadataStore.namingConvention);
    return em;
}
